#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

#define SN_D0_PIN GPIO_PIN_10
#define SN_D1_PIN GPIO_PIN_3
#define SN_D2_PIN GPIO_PIN_5
#define SN_D3_PIN GPIO_PIN_4
#define SN_D4_PIN GPIO_PIN_10
#define SN_D5_PIN GPIO_PIN_8
#define SN_D6_PIN GPIO_PIN_9
#define SN_D7_PIN GPIO_PIN_7
#define SN_WE_PIN GPIO_PIN_6

#define SN_D0_GPIO_PORT GPIOA
#define SN_D1_GPIO_PORT GPIOB
#define SN_D2_GPIO_PORT GPIOB
#define SN_D3_GPIO_PORT GPIOB
#define SN_D4_GPIO_PORT GPIOB
#define SN_D5_GPIO_PORT GPIOA
#define SN_D6_GPIO_PORT GPIOA
#define SN_D7_GPIO_PORT GPIOC
#define SN_WE_GPIO_PORT GPIOB

#define YM3438_GPIO_MUX_S0_PIN
#define YM3438_GPIO_MUX_S1_PIN
#define YM3438_GPIO_MUX_S2_PIN
#define YM3438_GPIO_CS_PIN
// #define YM3438_GPIO_RD_PIN
#define YM3438_GPIO_WR_PIN
#define YM3438_GPIO_A1_PIN
#define YM3438_GPIO_A0_PIN

#define YM3438_GPIO_MUX_S0_PORT GPIOA
#define YM3438_GPIO_MUX_S1_PORT GPIOA
#define YM3438_GPIO_MUX_S2_PORT GPIOA
#define YM3438_GPIO_CS_PORT GPIOA
// #define YM3438_GPIO_RD_PORT GPIOA
#define YM3438_GPIO_WR_PORT GPIOA
#define YM3438_GPIO_A1_PORT GPIOA
#define YM3438_GPIO_A0_PORT GPIOA

#endif